In [22]:
import numpy as np

In [23]:
a = np.random.rand(5,4)*100
b = np.random.rand(3,4)*100

In [24]:
print(a)

[[88.63295153 93.53813644 85.44744237 12.81422181]
 [59.56772495 77.19126043 12.58361084 98.71550307]
 [92.92212244 29.18719595 30.3758058  61.56195572]
 [13.33736281 72.97526373 79.33618078 23.21640625]
 [88.07805173 29.02106491 99.21752536 64.65396395]]


In [25]:
print(b)

[[50.65953365 47.78635793 31.54356837 14.26897573]
 [15.00943818 78.64929108 71.02313208 99.45249584]
 [72.25273758 71.66753308 53.24387995 81.03681056]]


In [26]:
c = np.concatenate((a, b))

In [27]:
print(c)

[[88.63295153 93.53813644 85.44744237 12.81422181]
 [59.56772495 77.19126043 12.58361084 98.71550307]
 [92.92212244 29.18719595 30.3758058  61.56195572]
 [13.33736281 72.97526373 79.33618078 23.21640625]
 [88.07805173 29.02106491 99.21752536 64.65396395]
 [50.65953365 47.78635793 31.54356837 14.26897573]
 [15.00943818 78.64929108 71.02313208 99.45249584]
 [72.25273758 71.66753308 53.24387995 81.03681056]]


In [28]:
d = np.random.rand(10,10)*5

In [29]:
print(d)

[[4.14743602 4.31165422 3.6553145  0.98047744 3.43693073 0.81274662
  0.09603674 1.93497169 0.4615175  4.54195294]
 [0.9947483  1.39671239 0.10463506 4.92787021 1.95921838 4.85816027
  2.88473472 3.28805365 1.04410294 1.90438046]
 [0.65128464 1.09060522 1.0956497  2.30368236 3.69027976 3.95518758
  1.10526694 0.64423985 1.34130526 1.30395928]
 [2.74037866 3.74276164 4.5917006  2.33404909 0.36085527 4.22001919
  1.17153985 1.10553184 3.65613848 1.98954565]
 [3.440352   2.58366806 4.25563633 4.11820781 3.44584708 1.17573987
  4.89689931 2.88274295 4.00787558 0.19501398]
 [0.25993183 2.56596711 3.10284344 0.67671061 1.11978791 0.38779975
  1.45155387 0.45799112 1.84147959 4.45378   ]
 [1.39108951 0.79550703 3.36144478 4.7994045  2.50630006 0.83277921
  3.80555283 3.53315716 3.88869471 1.39208881]
 [4.79672072 0.28171832 2.15599488 1.11342321 1.32555892 0.78474818
  1.36926513 3.12864813 0.25024183 4.84891039]
 [3.18871675 2.64581348 2.24353763 1.70982135 1.19690025 3.33097416
  3.76684674

In [30]:
print(np.matrix.transpose(a))

[[88.63295153 59.56772495 92.92212244 13.33736281 88.07805173]
 [93.53813644 77.19126043 29.18719595 72.97526373 29.02106491]
 [85.44744237 12.58361084 30.3758058  79.33618078 99.21752536]
 [12.81422181 98.71550307 61.56195572 23.21640625 64.65396395]]


In [31]:
print(np.matrix.transpose(b))

[[50.65953365 15.00943818 72.25273758]
 [47.78635793 78.64929108 71.66753308]
 [31.54356837 71.02313208 53.24387995]
 [14.26897573 99.45249584 81.03681056]]


In [32]:
print(np.matrix.transpose(c))

[[88.63295153 59.56772495 92.92212244 13.33736281 88.07805173 50.65953365
  15.00943818 72.25273758]
 [93.53813644 77.19126043 29.18719595 72.97526373 29.02106491 47.78635793
  78.64929108 71.66753308]
 [85.44744237 12.58361084 30.3758058  79.33618078 99.21752536 31.54356837
  71.02313208 53.24387995]
 [12.81422181 98.71550307 61.56195572 23.21640625 64.65396395 14.26897573
  99.45249584 81.03681056]]


In [33]:
print(np.matrix.transpose(d))

[[4.14743602 0.9947483  0.65128464 2.74037866 3.440352   0.25993183
  1.39108951 4.79672072 3.18871675 0.18618623]
 [4.31165422 1.39671239 1.09060522 3.74276164 2.58366806 2.56596711
  0.79550703 0.28171832 2.64581348 1.86179991]
 [3.6553145  0.10463506 1.0956497  4.5917006  4.25563633 3.10284344
  3.36144478 2.15599488 2.24353763 3.71992631]
 [0.98047744 4.92787021 2.30368236 2.33404909 4.11820781 0.67671061
  4.7994045  1.11342321 1.70982135 1.15056459]
 [3.43693073 1.95921838 3.69027976 0.36085527 3.44584708 1.11978791
  2.50630006 1.32555892 1.19690025 3.94963307]
 [0.81274662 4.85816027 3.95518758 4.22001919 1.17573987 0.38779975
  0.83277921 0.78474818 3.33097416 4.76241798]
 [0.09603674 2.88473472 1.10526694 1.17153985 4.89689931 1.45155387
  3.80555283 1.36926513 3.76684674 4.16300006]
 [1.93497169 3.28805365 0.64423985 1.10553184 2.88274295 0.45799112
  3.53315716 3.12864813 3.00112946 2.7912158 ]
 [0.4615175  1.04410294 1.34130526 3.65613848 4.00787558 1.84147959
  3.88869471