In [129]:
import numpy as np
import pandas as pd

In [130]:
print("Multistage Graph\n")
size = int(input("Enter number of Nodes : " ))

stage = []
stage.append(0)
#Taking stage of vertices
for i in range(1,size+1):
  v = int(input(f"Enter stage of vertex {i} : "))
  stage.append(v)

#printing vertex,stage
for i in range(1,size+1):
  print(f"vertex {i} : stage {stage[i-1]}")

#initializing  adj matrix to zero
c = np.zeros((size+1,size+1))

#taking cost according to the constraints 
for j in range(1,size+1):
  for i in range(1,size+1):
    v = []
    if stage[j] + 1 == stage[i]:
      
      c[j][i] = int(input(f'Enter cost from {j} to {i} : '))
print(c)


Multistage Graph

Enter number of Nodes : 7
Enter stage of vertex 1 : 1
Enter stage of vertex 2 : 2
Enter stage of vertex 3 : 2
Enter stage of vertex 4 : 2
Enter stage of vertex 5 : 3
Enter stage of vertex 6 : 3
Enter stage of vertex 7 : 4
vertex 1 : stage 0
vertex 2 : stage 1
vertex 3 : stage 2
vertex 4 : stage 2
vertex 5 : stage 2
vertex 6 : stage 3
vertex 7 : stage 3
Enter cost from 1 to 2 : 9
Enter cost from 1 to 3 : 7
Enter cost from 1 to 4 : 3
Enter cost from 2 to 5 : 4
Enter cost from 2 to 6 : 2
Enter cost from 3 to 5 : 2
Enter cost from 3 to 6 : 7
Enter cost from 4 to 5 : 0
Enter cost from 4 to 6 : 8
Enter cost from 5 to 7 : 3
Enter cost from 6 to 7 : 6
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 9. 7. 3. 0. 0. 0.]
 [0. 0. 0. 0. 0. 4. 2. 0.]
 [0. 0. 0. 0. 0. 2. 7. 0.]
 [0. 0. 0. 0. 0. 0. 8. 0.]
 [0. 0. 0. 0. 0. 0. 0. 3.]
 [0. 0. 0. 0. 0. 0. 0. 6.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [131]:
c = c.astype(int)
print(c)

[[0 0 0 0 0 0 0 0]
 [0 0 9 7 3 0 0 0]
 [0 0 0 0 0 4 2 0]
 [0 0 0 0 0 2 7 0]
 [0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 3]
 [0 0 0 0 0 0 0 6]
 [0 0 0 0 0 0 0 0]]


In [132]:
#creating and converting cost and d arrays
cost = np.zeros(size+1)
d = np.zeros(size+1)
print(f'{d} and {cost}')
cost = cost.astype(int)
d = d.astype(int)
print(f'{d} and {cost}')

[0. 0. 0. 0. 0. 0. 0. 0.] and [0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0] and [0 0 0 0 0 0 0 0]


In [133]:
#initializing last values of cost and d array
d[size] = size
cost[size] = 0

In [134]:
for i in range(size-1,0,-1):
  min = 9999
  for k in range(i+1,size+1):
    if c[i][k] != 0 and c[i][k] + cost[k] < min:
      min = c[i][k] + cost[k]
      d[i] = k
    
  cost[i] = min

p = np.zeros(size+1)
p = p.astype(int)
p[1] = 1
p[stage[len(stage) -1]] = size



for i in range(2, stage[len(stage)-1]):
 
  p[i] = d[p[i-1]]

print(np.trim_zeros(p))
    


[1 3 5 7]
